import type { Metadata } from "next";
import ClientWrapper from "./ClientWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fusionera",
  description: "Generated by Fusionera app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper>
          {children}
        </ClientWrapper>
      </body>
    </html>
  )
}
